server: # REST and WS server
  port: 2333
  address: 127.0.0.1 # your actual server address
                     # if you want to expose it to
                     # the internet
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "someStrongPasswordHere"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      mixer: false
      http: false
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 100MB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
